mkdir -p ./mab/raw/canc/bladr/seqs/
mkdir -p ./mab/raw/canc/bladr/gtyp/
mkdir -p ./mab/raw/canc/bladr/micr/
mkdir -p ./mab/raw/canc/bladr/facs/
mkdir -p ./mab/raw/canc/bladr/imgs/
mkdir -p ./mab/raw/canc/bladr/nums/
mkdir -p ./mab/raw/canc/bladr/vari/
mkdir -p ./mab/raw/canc/bladr/seqs/wgs/tum
mkdir -p ./mab/raw/canc/bladr/seqs/wgs/mar
mkdir -p ./mab/raw/canc/bladr/seqs/wgs/bld
mkdir -p ./mab/raw/canc/bladr/seqs/wgs/ctr
mkdir -p ./mab/raw/canc/bladr/seqs/rna/tum
mkdir -p ./mab/raw/canc/bladr/seqs/rna/mar
mkdir -p ./mab/raw/canc/bladr/seqs/rna/bld
mkdir -p ./mab/raw/canc/bladr/seqs/rna/ctr
mkdir -p ./mab/raw/canc/bladr/seqs/met/tum
mkdir -p ./mab/raw/canc/bladr/seqs/met/mar
mkdir -p ./mab/raw/canc/bladr/seqs/met/bld
mkdir -p ./mab/raw/canc/bladr/seqs/met/ctr
mkdir -p ./mab/raw/canc/bladr/seqs/exo/tum
mkdir -p ./mab/raw/canc/bladr/seqs/exo/mar
mkdir -p ./mab/raw/canc/bladr/seqs/exo/bld
mkdir -p ./mab/raw/canc/bladr/seqs/exo/ctr
mkdir -p ./mab/raw/canc/bladr/seqs/tgt/tum
mkdir -p ./mab/raw/canc/bladr/seqs/tgt/mar
mkdir -p ./mab/raw/canc/bladr/seqs/tgt/bld
mkdir -p ./mab/raw/canc/bladr/seqs/tgt/ctr
mkdir -p ./mab/raw/canc/bladr/seqs/oth/tum
mkdir -p ./mab/raw/canc/bladr/seqs/oth/mar
mkdir -p ./mab/raw/canc/bladr/seqs/oth/bld
mkdir -p ./mab/raw/canc/bladr/seqs/oth/ctr
mkdir -p ./mab/raw/canc/brest/seqs/
mkdir -p ./mab/raw/canc/brest/gtyp/
mkdir -p ./mab/raw/canc/brest/micr/
mkdir -p ./mab/raw/canc/brest/facs/
mkdir -p ./mab/raw/canc/brest/imgs/
mkdir -p ./mab/raw/canc/brest/nums/
mkdir -p ./mab/raw/canc/brest/vari/
mkdir -p ./mab/raw/canc/brest/seqs/wgs/tum
mkdir -p ./mab/raw/canc/brest/seqs/wgs/mar
mkdir -p ./mab/raw/canc/brest/seqs/wgs/bld
mkdir -p ./mab/raw/canc/brest/seqs/wgs/ctr
mkdir -p ./mab/raw/canc/brest/seqs/rna/tum
mkdir -p ./mab/raw/canc/brest/seqs/rna/mar
mkdir -p ./mab/raw/canc/brest/seqs/rna/bld
mkdir -p ./mab/raw/canc/brest/seqs/rna/ctr
mkdir -p ./mab/raw/canc/brest/seqs/met/tum
mkdir -p ./mab/raw/canc/brest/seqs/met/mar
mkdir -p ./mab/raw/canc/brest/seqs/met/bld
mkdir -p ./mab/raw/canc/brest/seqs/met/ctr
mkdir -p ./mab/raw/canc/brest/seqs/exo/tum
mkdir -p ./mab/raw/canc/brest/seqs/exo/mar
mkdir -p ./mab/raw/canc/brest/seqs/exo/bld
mkdir -p ./mab/raw/canc/brest/seqs/exo/ctr
mkdir -p ./mab/raw/canc/brest/seqs/tgt/tum
mkdir -p ./mab/raw/canc/brest/seqs/tgt/mar
mkdir -p ./mab/raw/canc/brest/seqs/tgt/bld
mkdir -p ./mab/raw/canc/brest/seqs/tgt/ctr
mkdir -p ./mab/raw/canc/brest/seqs/oth/tum
mkdir -p ./mab/raw/canc/brest/seqs/oth/mar
mkdir -p ./mab/raw/canc/brest/seqs/oth/bld
mkdir -p ./mab/raw/canc/brest/seqs/oth/ctr
mkdir -p ./mab/raw/canc/colon/seqs/
mkdir -p ./mab/raw/canc/colon/gtyp/
mkdir -p ./mab/raw/canc/colon/micr/
mkdir -p ./mab/raw/canc/colon/facs/
mkdir -p ./mab/raw/canc/colon/imgs/
mkdir -p ./mab/raw/canc/colon/nums/
mkdir -p ./mab/raw/canc/colon/vari/
mkdir -p ./mab/raw/canc/colon/seqs/wgs/tum
mkdir -p ./mab/raw/canc/colon/seqs/wgs/mar
mkdir -p ./mab/raw/canc/colon/seqs/wgs/bld
mkdir -p ./mab/raw/canc/colon/seqs/wgs/ctr
mkdir -p ./mab/raw/canc/colon/seqs/rna/tum
mkdir -p ./mab/raw/canc/colon/seqs/rna/mar
mkdir -p ./mab/raw/canc/colon/seqs/rna/bld
mkdir -p ./mab/raw/canc/colon/seqs/rna/ctr
mkdir -p ./mab/raw/canc/colon/seqs/met/tum
mkdir -p ./mab/raw/canc/colon/seqs/met/mar
mkdir -p ./mab/raw/canc/colon/seqs/met/bld
mkdir -p ./mab/raw/canc/colon/seqs/met/ctr
mkdir -p ./mab/raw/canc/colon/seqs/exo/tum
mkdir -p ./mab/raw/canc/colon/seqs/exo/mar
mkdir -p ./mab/raw/canc/colon/seqs/exo/bld
mkdir -p ./mab/raw/canc/colon/seqs/exo/ctr
mkdir -p ./mab/raw/canc/colon/seqs/tgt/tum
mkdir -p ./mab/raw/canc/colon/seqs/tgt/mar
mkdir -p ./mab/raw/canc/colon/seqs/tgt/bld
mkdir -p ./mab/raw/canc/colon/seqs/tgt/ctr
mkdir -p ./mab/raw/canc/colon/seqs/oth/tum
mkdir -p ./mab/raw/canc/colon/seqs/oth/mar
mkdir -p ./mab/raw/canc/colon/seqs/oth/bld
mkdir -p ./mab/raw/canc/colon/seqs/oth/ctr
mkdir -p ./mab/raw/canc/prost/seqs/
mkdir -p ./mab/raw/canc/prost/gtyp/
mkdir -p ./mab/raw/canc/prost/micr/
mkdir -p ./mab/raw/canc/prost/facs/
mkdir -p ./mab/raw/canc/prost/imgs/
mkdir -p ./mab/raw/canc/prost/nums/
mkdir -p ./mab/raw/canc/prost/vari/
mkdir -p ./mab/raw/canc/prost/seqs/wgs/tum
mkdir -p ./mab/raw/canc/prost/seqs/wgs/mar
mkdir -p ./mab/raw/canc/prost/seqs/wgs/bld
mkdir -p ./mab/raw/canc/prost/seqs/wgs/ctr
mkdir -p ./mab/raw/canc/prost/seqs/rna/tum
mkdir -p ./mab/raw/canc/prost/seqs/rna/mar
mkdir -p ./mab/raw/canc/prost/seqs/rna/bld
mkdir -p ./mab/raw/canc/prost/seqs/rna/ctr
mkdir -p ./mab/raw/canc/prost/seqs/met/tum
mkdir -p ./mab/raw/canc/prost/seqs/met/mar
mkdir -p ./mab/raw/canc/prost/seqs/met/bld
mkdir -p ./mab/raw/canc/prost/seqs/met/ctr
mkdir -p ./mab/raw/canc/prost/seqs/exo/tum
mkdir -p ./mab/raw/canc/prost/seqs/exo/mar
mkdir -p ./mab/raw/canc/prost/seqs/exo/bld
mkdir -p ./mab/raw/canc/prost/seqs/exo/ctr
mkdir -p ./mab/raw/canc/prost/seqs/tgt/tum
mkdir -p ./mab/raw/canc/prost/seqs/tgt/mar
mkdir -p ./mab/raw/canc/prost/seqs/tgt/bld
mkdir -p ./mab/raw/canc/prost/seqs/tgt/ctr
mkdir -p ./mab/raw/canc/prost/seqs/oth/tum
mkdir -p ./mab/raw/canc/prost/seqs/oth/mar
mkdir -p ./mab/raw/canc/prost/seqs/oth/bld
mkdir -p ./mab/raw/canc/prost/seqs/oth/ctr
